# Generated by Django 3.2.6 on 2021-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
