# Generated by Django 3.2.6 on 2021-08-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_likes_song_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='like',
            new_name='likes',
        ),
    ]
